"""Add lineups cache table

Revision ID: e82effb2c988
Revises: 18dff737b74d
Create Date: 2026-02-13 19:21:31.824910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e82effb2c988'
down_revision: Union[str, Sequence[str], None] = '18dff737b74d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lineup_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_api_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_api_id', 'event_id', name='uq_player_event_lineup')
    )
    op.create_index(op.f('ix_lineup_cache_event_id'), 'lineup_cache', ['event_id'], unique=False)
    op.create_index(op.f('ix_lineup_cache_id'), 'lineup_cache', ['id'], unique=False)
    op.create_index(op.f('ix_lineup_cache_player_api_id'), 'lineup_cache', ['player_api_id'], unique=False)
    op.alter_column('player_season_stats', 'season',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('player_season_stats', 'season_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_season_stats', sa.Column('season_text', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('player_season_stats', 'season',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_lineup_cache_player_api_id'), table_name='lineup_cache')
    op.drop_index(op.f('ix_lineup_cache_id'), table_name='lineup_cache')
    op.drop_index(op.f('ix_lineup_cache_event_id'), table_name='lineup_cache')
    op.drop_table('lineup_cache')
    # ### end Alembic commands ###
